[package]
name = "aoc-2015"
version = "0.1.0"
edition = "2021"

[dependencies]
aoc-lib = { path = "../aoc-lib" }
anyhow = "1.0"
md-5 = "0.10.6"
regex = "1.11.1"

[[bin]]
name = "main"
path = "src/main.rs"
