[package]
name = "aoc-2016"
version = "0.1.0"
edition = "2021"

[dependencies]
aoc-lib = { path = "../aoc-lib" }
anyhow = "1.0"
regex = "1.11.1"
md5 = "0.8.0"

[[bin]]
name = "main"
path = "src/main.rs"
